-- Capacity Connect Supabase schema
-- Run this file in Supabase SQL Editor.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    name text not null,
    email text not null unique,
    registration_number text not null unique,
    role text not null default 'trainee' check (role in ('trainee', 'trainer', 'admin')),
    approved boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.courses (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null,
    duration text,
    modules integer,
    description text not null,
    trainer_id uuid not null references public.profiles(id),
    published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    title text not null,
    message text not null,
    author_id uuid not null references public.profiles(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.enrollments (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    course_id bigint not null references public.courses(id) on delete cascade,
    progress integer not null default 0 check (progress between 0 and 100),
    created_at timestamptz not null default now(),
    unique (user_id, course_id)
);

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.announcements enable row level security;
alter table public.enrollments enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'admin' and approved = true
    );
$$;

create policy "Approved profiles are publicly visible"
on public.profiles for select
using (approved = true or id = auth.uid() or public.is_admin());

create policy "Users can create their own profile"
on public.profiles for insert
with check (id = auth.uid() and role = 'trainee' and approved = false);

create policy "Users can update their own profile"
on public.profiles for update
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

create policy "Everyone can view published courses"
on public.courses for select
using (published = true or trainer_id = auth.uid() or public.is_admin());

create policy "Trainers can publish courses"
on public.courses for insert
with check (
    trainer_id = auth.uid()
    and exists (
        select 1 from public.profiles
        where id = auth.uid()
        and approved = true
        and role in ('trainer', 'admin')
    )
);

create policy "Trainers can update their own courses"
on public.courses for update
using (trainer_id = auth.uid() or public.is_admin())
with check (trainer_id = auth.uid() or public.is_admin());

create policy "Everyone can view announcements"
on public.announcements for select
using (true);

create policy "Approved users can publish announcements"
on public.announcements for insert
with check (author_id = auth.uid());

create policy "Users can view their enrollments"
on public.enrollments for select
using (user_id = auth.uid() or public.is_admin());

create policy "Users can create their own enrollments"
on public.enrollments for insert
with check (user_id = auth.uid());

alter table public.courses replica identity full;
alter table public.announcements replica identity full;

-- Enable realtime from the Supabase dashboard for courses and announcements.
